name: 'Create JIRA Ticket'
description: 'Creates a JIRA ticket based on a GitHub issue or pull request comment'
inputs:
  jira_url:
    description: 'The URL of the JIRA instance'
    required: true
  jira_api_token:
    description: 'API token for authenticating with JIRA'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.jira_url }}
    - ${{ inputs.jira_api_token }}
    - ${{ inputs.jira_api_user }}