name: 'Create JIRA Ticket'
description: 'Создает JIRA-тикет при добавлении специального комментария'
inputs:
  jira_url:
    description: 'URL JIRA сервера'
    required: true
  jira_api_token:
    description: 'JIRA API токен'
    required: true
  github-token:
    description: 'GitHub токен'
    required: true
  command:
    description: 'Команда для создания JIRA тикета'
    required: true
    default: '/create-jira'
runs:
  using: 'composite'
  steps:
    - name: Run Groovy Script
      run: groovy src/main/groovy/com/example/GroovyScript.groovy
      shell: bash
