name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew
      - run: ./gradlew build
      - name: Upload JUnit test reports on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: junit-test-reports
          path: build/test-results/test/*.xml

      - name: Publish JUnit test results on failure
        if: failure()
        uses: actions/upload-junit-report@v2
        with:
          report_paths: build/test-results/test/*.xml