name: Use Create JIRA Action

on:
  issue_comment:
    types: [created]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/create-jira')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Create JIRA Action
        uses: tkachenkoas/create-jira@0.1.10
        with:
          jira_url: ${{ secrets.JIRA_URL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}