name: Use Create JIRA Action

on:
  issue_comment:
    types: [created]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    # so that not to run the action on every comment
    if: startsWith(github.event.comment.body, '/create-jira')

    steps:
      - name: Use Create JIRA Action
        uses: tkachenkoas/create-jira@1.0.0
        with:
          jira_url: https://tkachenkoas.atlassian.net
          jira_api_user: tkachenkoas@gmail.com
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}